services:
  postgres_db:
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data_uds:/var/lib/postgresql # For PostgresSQL >= 17

volumes:
  postgres_data_uds:
